### ISSUE TITLE
Validator - readTileset

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles-tools#10]
@sumitshyamsukha

Write a lib file called `readTileset` that loads a `tileset.json` file, check that the contents are valid JSON, and return the JSON object. Throw an error if the JSON is not valid.

**Comment by sumitshyamsukha** [comment]
Don't have access to push yet -- could I be granted access? @lilleyse

**Comment by lilleyse** [comment]
Thanks for the reminder, you and @JudyWeng are added now.

**Comment by FreakTheMighty** [comment]
Sorry to bring back a very old ticket, but I wonder if it would be worth using something a json-schema library like [this](https://ajv.js.org/) to handle basic validation.
