### ISSUE TITLE
how to decide the location of generated building samples

### ISSUE THREAD

**Issue by yiqunc** [AnalyticalGraphicsInc/3d-tiles-tools#132]
I am trying to understand how to locate the generated buildings in "bin/b3d-tiles-samples-generator-original.js" and get confused. In line 41 - 42, it defines:
var longitude = -1.31968;
var latitude = 0.698874;
but that point is in the sea while the generated buildings are located on the land 
![capture](https://user-images.githubusercontent.com/2689849/33404212-8feb6a44-d5b7-11e7-9297-0a19341d728a.JPG)
![capture2](https://user-images.githubusercontent.com/2689849/33404385-3831750e-d5b8-11e7-9a0c-aa7e8019f6c2.JPG)

The lon and lat values clearly impact to the location of generated buildings, but how it actually works? How can we put the buildings at the exact location? I also checked the created tileset.json, the region in boundingVolume of root looks right. 

{
  "asset": {
    "version": "0.0"
  },
  "geometricError": 70,
  "root": {
    "refine": "ADD",
    "boundingVolume": {
      "region": [
        -1.3197004795898053,
        0.6988582109,
        -1.3196595204101946,
        0.6988897891,
        0,
        20
      ]
    },
    "geometricError": 0,
    "content": {
      "url": "batchedWithBatchTable.b3dm"
    }
  }
}

**Comment by lilleyse** [comment]
The longitude and latitude are defined in radians, after converting to degrees you'll see that it's in the correct location.

**Comment by yiqunc** [comment]
oh, I didn't realize that, thanks @lilleyse , now it works like a charm!
![3d tiles single bim model](https://user-images.githubusercontent.com/2689849/33508503-cf37ad46-d74e-11e7-80e7-7b8f25e4dd28.jpg)

**Comment by lilleyse** [comment]
Nice!
