### ISSUE TITLE
after gzip  3dtiles,cesium can not load

### ISSUE THREAD

**Issue by wlhm1984** [AnalyticalGraphicsInc/3d-tiles-tools#133]
after gzip  3dtiles,cesium can not load, need other setting?thanks

**Comment by lilleyse** [comment]
If you are using your own server you will need to mark the tileset files as gzipped before serving them.

**Comment by Frank-Chan** [comment]
I met the same problem. I want to know how to mark the tileset files as gzipped?

**Comment by lilleyse** [comment]
It depends on your server setup.

If you want a quick way to serve tilesets locally that are gzipped (or not) you can use the server in [3d-tiles-samples](https://github.com/AnalyticalGraphicsInc/3d-tiles-samples)

**Comment by Frank-Chan** [comment]
@lilleyse My web server is **apache-tomcat-6.0.4**, is it support gzipped 3d tiles?
And I also tried node.js server, this one is supported.

**Comment by lilleyse** [comment]
You will have to look at the Tomcat documentation for how to mark certain file types as gzipped. In particularly you will want to mark `tileset.json` and `.b3dm` files as gzipped.

**Comment by Frank-Chan** [comment]
@lilleyse I  load a tileset with Cesium use the code below, the same to node.js server, but I didn't know which piece of code is the **mark** as gzipped for node.js.  Please point it out for me?
`
var viewer = new Cesium.Viewer('cesiumContainer');

var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url : 'http://localhost:8003/tilesets/TilesetWithDiscreteLOD/'
}));

tileset.readyPromise.then(function(tileset) {
    viewer.camera.viewBoundingSphere(tileset.boundingSphere, new Cesium.HeadingPitchRange(0, -0.5, 0));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
});`

**Comment by lilleyse** [comment]
For the server in `3d-tiles-tools` the gzip code is here: https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/blob/master/server.js#L61-L77. However this check is a bit slow and I wouldn't include it in production.

For other servers it may be in a configuration file. For Tomcat check out https://www.codeproject.com/Articles/1201188/Apache-Tomcat-Enable-gzip-Compression-and-Expires.
