### ISSUE TITLE
Tools - Is there any tool process an entire tileset? 

### ISSUE THREAD

**Issue by Frank-Chan** [AnalyticalGraphicsInc/3d-tiles-tools#138]
https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/blob/afb9decfcc64f14cb96001168617fc8c10f6298f/tools/lib/glbToB3dm.js#L21
> glbToB3dm
> Creates a b3dm from a glb with an empty batch table. Since this tool does not process an entire tileset, it cannot be used with the Pipeline tool.
## Is there any tool can process an entire tileset? 
The B3dm created by current **glbToB3dm tool** can't generate featuretable and batchtable. So I can't use the getproperty() method to get the model's _Name, ID_ and other properties(The result is shown in Fig.1). However, I can get the [cesiumjs.org's model ](url: 'https://beta.cesium.com/api/assets/1461?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkYWJmM2MzNS02OWM5LTQ3OWItYjEyYS0xZmNlODM5ZDNkMTYiLCJpZCI6NDQsImFzc2V0cyI6WzE0NjFdLCJpYXQiOjE0OTkyNjQ3NDN9.vuR75SqPDKcggvUrG_vpx0Av02jdiAxnnB1fNf-9f7s')property with the same method(The result is shown in Fig.2).
Is there any tool can convert _gltf_ or _glb_ to complete [_b3dm_ file, which contains _Feature Table_ and _Batch Table_.](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel)

![getproperty undifined](https://user-images.githubusercontent.com/8639688/37188509-82e3d284-238a-11e8-8dd6-0707e0dbeecf.png)
  Fig.1 b3dm converted by glb2b3dm comandline from _3d tiles tools_
![getproperty success](https://user-images.githubusercontent.com/8639688/37189867-7dbfef7a-2391-11e8-8764-76f744a1af4f.png)
  Fig.2 b3dm file from [sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Picking.html&label=Showcases)

**Comment by lilleyse** [comment]
Currently `3d-tiles-tools` doesn't have a function like that which takes a glTF/glb, extracts features from it, and creates a b3dm with a batch table and feature table. Part of the problem is in identifying which parts of the model should be split into features and then getting metadata from the model.

Typically its easier to create 3D Tiles from source data like CityGML.

**Comment by Frank-Chan** [comment]
Thanks a lot! But I want to get a model's _ID_, and then mark that specified model's name, color and for  further processing.
By the way, my 3D Tiles are created from 3dsMax files, there are so many  heterogeneous 3D building models.

**Comment by Frank-Chan** [comment]
@lilleyse 
Thanks a lot! But I want to get a model's ID, and then mark that specified model's name, color and for further processing.
By the way, my 3D Tiles are created from 3dsMax files, there are so many heterogeneous 3D building models.

**Comment by lilleyse** [comment]
Thanks for the clarification, however I'm not aware of a tool that does that.

**Comment by Frank-Chan** [comment]
Well, thank you all the same.
