### ISSUE TITLE
glb to b3dm ?

### ISSUE THREAD

**Issue by X-DX** [AnalyticalGraphicsInc/3d-tiles-tools#146]
please anyone tell me how to create a B3DM file only for particular region ?
i have only glb file ... so what can i do to get a b3dm file ... and run it on cesium

like in the gltf we can make a objects(buildings) using sketchup tool .
like a same way how can I make this objects and create a b3dm file of the particular region .
please help.

**Comment by lilleyse** [comment]
Hi @X-DX - see my response in the other thread: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/issues/20#issuecomment-397819356

In general questions like this are also better to post on the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).
