### ISSUE TITLE
Validator - Validate tiles referenced in tileset.json

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles-tools#35]
@sumitshyamsukha 

When traversing the tileset.json, if the tile's content references a url, load that tile into memory, check its magic to determine its type, and then check if it is valid according to the `validateB3dm`, `validateI3dm`, `validatePnts`, and `validateCmpt` functions.

`validateCmpt` is not in yet but should be soon. You can model the functionality here after the code in there.

The trickiest part will be managing the promises. Let me know if you need help with that.

**Comment by sumitshyamsukha** [comment]
@lilleyse How should I go about loading the tile into memory? Just use a variable or is there a better way? Also, should it be valid according to all of the 4 mentioned functions, or any one of them? Thanks!

**Comment by lilleyse** [comment]
You can use the `readTile` function that will give you a Buffer object. Based on the magic in the tile's header, it will check only one of the 4 functions.
