### ISSUE TITLE
Abort 3dtiles

### ISSUE THREAD

**Issue by mdfazh** [AnalyticalGraphicsInc/3d-tiles-tools#50]
How can I make a tileset by my own collada(*.dae)?

**Comment by lilleyse** [comment]
You can use the [COLLADA2GLTF converter](https://github.com/KhronosGroup/COLLADA2GLTF). Once you have glTF models you can create [b3dm tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel). Then you just need to create a `tileset.json` file that describes the positioning and hierarhcy of the models.

The [3D Tiles Spec](https://github.com/AnalyticalGraphicsInc/3d-tiles) is the best place to start for learning about the format.

**Comment by mdfazh** [comment]
Thanks,lilleyse! Let me try！

**Comment by mdfazh** [comment]
Hi,lilleyse!Could you tell me how can I create b3dm tiles by glTF models? Thanks!

**Comment by lilleyse** [comment]
The models need to be in binary glTF format. Then the code looks similar to https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/blob/master/generator/lib/createB3dm.js.

Additionally there's a `glbToB3dm` tool in [3d-tiles-tools](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/tools).
