### ISSUE TITLE
Unpack a .3dtiles database file

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles-tools#56]
It would be convenient to have a stage that takes a `.3dtiles` file and unpacks it to a tileset folder. It should ungzip tiles in the database.

**Comment by mramato** [comment]
👍 I just went looking for this and was sad to see we don't have it yet.

**Comment by lilleyse** [comment]
Soon - https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/62
