### ISSUE TITLE
glbToB3dm

### ISSUE THREAD

**Issue by ailmee** [AnalyticalGraphicsInc/3d-tiles-tools#64]
E:\3d-tiles-tools-master\tools>node ./bin/3d-tiles-tools.js glbToB3dm ./specs/data/CesiumTexturedBox/CesiumTexturedBox.glb ./output/CesiumTexturedBox.b3dm
Buffer.alloc is not a function

How to solve this problem？

**Comment by lilleyse** [comment]
Try upgrade to Node version 4.5.0 or greater.

**Comment by ailmee** [comment]
Thank you. I'll try
