### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by freder** [AnalyticalGraphicsInc/3d-tiles-tools#67]
... so that `3d-tiles-tools` can be installed as a dependency.

**Comment by lilleyse** [comment]
The root folder is more like a container for three different projects that have their own package.json. The `tools` folder is available on npm as `3d-tiles-tools`

**Comment by freder** [comment]
oh, somehow I have overlooked the `package.json` in the sub-directories. — I'm working on s.th. that generates 3d tiles from a database, so I am using functionality from `generator`.

**Comment by lilleyse** [comment]
I don't expect the `generator` project to be made into an npm package / API since it is pretty specific to generating samples in Cesium and `3d-tiles-samples`. The code is more instructional than API focused.
