### ISSUE TITLE
How to generate .pnts file using this tool?

### ISSUE THREAD

**Issue by salutonalpha** [AnalyticalGraphicsInc/3d-tiles-tools#73]
I would like to know how to use this tool to produce .pnts file for my custom .laz data?

**Comment by lilleyse** [comment]
At the moment the tools here do not do LAZ to 3D Tiles conversions.

**Comment by lilleyse** [comment]
However we are developing tools for conversions like this and are always looking for datasets to test with. Feel free to email me at slilley@agi.com if you are interested.

**Comment by salutonalpha** [comment]
Thank you for reply

I have found the tools 'entwine-cesium-pages' which can meet my needs.
