### ISSUE TITLE
npm install error,please help me!~

### ISSUE THREAD

**Issue by Flying-a-Fish** [AnalyticalGraphicsInc/3d-tiles-tools#77]
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1018:11)
gyp ERR! stack     at TLSWrap.onread (net.js:568:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Users\\Administrator\\Desktop\\3d-tiles-tools-ma
ster\\tools\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64\\node_sqlit
e3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Administrator\\D
esktop\\3d-tiles-tools-master\\tools\\node_modules\\sqlite3\\lib\\binding\\node-
v48-win32-x64"
gyp ERR! cwd C:\Users\Administrator\Desktop\3d-tiles-tools-master\tools\node_mod
ules\sqlite3
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\Users\Administrator\Desktop\3d-tiles-tools-master\tools
\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_
name=node_sqlite3 --module_path=C:\Users\Administrator\Desktop\3d-tiles-tools-ma
ster\tools\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\
Desktop\3d-tiles-tools-master\tools\node_modules\sqlite3\node_modules\node-pre-g
yp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admi
nistrator\\Desktop\\3d-tiles-tools-master\\tools\\node_modules\\sqlite3\\node_mo
dules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Administrator\Desktop\3d-tiles-tools-master\tools
\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\
Administrator\Desktop\3d-tiles-tools-master\tools\node_modules\sqlite3\lib\bindi
ng\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path
=C:\Users\Administrator\Desktop\3d-tiles-tools-master\tools\node_modules\sqlite3
\lib\binding\node-v48-win32-x64' (1)
3d-tiles-tools@0.1.3 C:\Users\Administrator\Desktop\3d-tiles-tools-master\tools

**Comment by lilleyse** [comment]
It looks like something went wrong with the `sqlite3` node module. This works for me on a clean install of node 6.10.1 which is similar to your version of 6.10.3. Maybe you can try installing node 4.8.3.

**Comment by lilleyse** [comment]
Closing for now, let us know if you are still having issues.
