### ISSUE TITLE
excuse me,I want to know how to convert .glb or .osgb to 3dtiles

### ISSUE THREAD

**Issue by Flying-a-Fish** [AnalyticalGraphicsInc/3d-tiles-tools#79]

**Comment by lilleyse** [comment]
Sorry for the late reply.

If you have glb models you can convert to b3dm tiles through the `glbToB3dm` tool here. However if you are looking to batch models together and build a tileset.json file, the tools here aren't really equipped for that.

If you have a large dataset you would like to convert, check out this thread on the Cesium forum: https://groups.google.com/forum/#!topic/cesium-dev/xLkYIuku9hA

**Comment by fanvanzh** [comment]
you can try my repository. a simple tool for osgb to 3dtile.
[here is the link](https://github.com/fanvanzh/3dtiles)

**Comment by CrashedBboy** [comment]
Hello @Flying-a-Fish  , I just create an online tool to tile single model into 3D Tiles.  
.glb (glTF) is one of the supported input format  
[http://www.3dtiler.com/](http://www.3dtiler.com/)  
If you want to tile your model which is bigger than 20MB(current upload limit), you can send me the file and I can tile it manually.

**Comment by bim2box** [comment]
Late in the party, but I'd like to share a cli tool that I created on https://bim2box.com, it supports converting osgb to 3dtiles with draco compression.
