### ISSUE TITLE
Can I convert a 3d model to 3D-Tiles directly from database (such as 3DCityDB or sqlite)?

### ISSUE THREAD

**Issue by salutonalpha** [AnalyticalGraphicsInc/3d-tiles-tools#89]
I would like to write a back-end to read data (3D model) from database and then convert 3D model to 3d-tile in application. Can I hide the 3D-Tiles export behind some web service interface using this 3d-tiles-tool?

**Comment by lilleyse** [comment]
Yes you can use `3d-tiles-tools` as an npm module if your web service is built with Node.

**Comment by salutonalpha** [comment]
Thanks a lot.
