### ISSUE TITLE
Validator - validateB3dm header

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles-tools#9]
@JudyWeng

Write a lib file called `validateB3dm` that takes a Buffer containing the contents of a b3dm (like as returned by `readTile`) and checks that it is valid according the the [b3dm spec](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel). For now just check that:

magic is "b3dm"
version is 1
byteLength is equal to the Buffer's length
batchTableJSONByteLength - skip for now, will require more validation later
batchTableBinaryByteLength - skip for now, will require more validation later
batchLength - skip for now, this is dependent on the glTF within the b3dm

This issue will get more involved and will eventually extend to the other tile formats.

**Comment by JudyWeng** [comment]
I tried to push earlier and it says I do not have access to 3d-tiles-tools. Am I supposed to push elsewhere?

**Comment by lilleyse** [comment]
Did you receive any emails about being added to the organization?

**Comment by JudyWeng** [comment]
oh sorry, yeah, it went to my spam box for some reason. Thanks!

**Comment by lilleyse** [comment]
Fixed in #14

**Comment by lilleyse** [comment]
And #16
