### ISSUE TITLE
Validator - check that geometric error exists

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles-tools#96]
@rms13

Check that geometric error is defined for every tile in the tree and it's value is `>= 0.0`. This should go before the `'Child has geometricError greater than parent'` check.

**Comment by rms13** [comment]
@lilleyse 

The test in `validateTilesetSpec.js`, currently does not display the actual error message (even for the `'Child has geometricError greater than parent'` check). This will cause confusion when adding more checks in the same function.

Should we change the test to display the actual error that caused the test failure?

**Comment by lilleyse** [comment]
Yeah the tests should show the error message that caused the failure. Also feel free to add a test for `Child has geometricError greater than parent` too.
